language: php
php:
  - 7.2
  - 7.3
  - 7.4
  - 'nightly'
dist: xenial
env:
  global:
    - MEMCACHED_HOST=localhost MEMCACHED_PORT=11211
    - REDIS_HOST=localhost REDIS_PORT=6379
services:
  - memcached
  - redis-server
before_install:
  - pecl channel-update pecl.php.net
  - echo yes | pecl install -f apcu
  - echo 'apc.enable_cli = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'extension = memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
before_script:
  - composer install --prefer-source --no-interaction
script:
  - vendor/bin/phpunit --coverage-clover=clover.xml
after_script:
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
  - php php-coveralls.phar --verbose
cache:
  directories:
    - $HOME/.composer/cache/files
after_success:
  - bash <(curl -s https://codecov.io/bash)